name: CI

on:
  push:
    branches:
      - "**" #double star includes a '/'.  single star doesnt match a '/'
    tags:
      - "**" #double star includes a '/'.  single star doesnt match a '/'
  schedule:
    # Daily at 05:44
    - cron: '44 5 * * *'

defaults:
  run:
    shell: bash

env:
  PYTHON_VERSION: 3.7
  PYTHON: c:/hostedtoolcache/windows/Python/3.7.9/x64


jobs:
  build:
    name: CI
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: recursive
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: python commands
        run: |
          set -vx
          which pip
          pip --version
          python boots.py create --group package
          venv/Scripts/black --check --diff .
          venv/Scripts/genbuildinfo "epyqlib/_build_generated.py"
          venv/Scripts/pip freeze --all

          ls
          ls ../

          venv/Scripts/autodevice create template --zip="artifacts/autodevice_template-$(venv/Scripts/python -c 'import epyq; print(f"{epyq.__version_tag__}-{epyq.__build_tag__}", end="")').zip"
          python boots.py build

          ls
          venv/Scripts/pytest -vvvv -s --no-qt-log --run-factory epyqlib.tests --pyargs

          python boots.py publish

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: epyq_st
          path: |
            ../dist/*